scenario: asu_campus_3p5
download: true

batch_size: 16
num_workers: 0
pin_memory: true

preprocess: ferrand  # 'ferrand' or 'dichasus'

train_num_users: 100
val_num_users: 100
test_num_users: 100
T_min: 20
T_max: 60
window: 500

compute_channels:
