scenario: city_3_houston_3p5
download: true

batch_size: 16
num_workers: 0
pin_memory: true

preprocess: ferrand  # 'ferrand' or 'dichasus'

exclude_buildings: true
inscribed_ellipse: true
pos_distance: 2
neg_distance: 40
trajectory_kind: coherent
heading_momentum: 0.7
train_num_users: 1
val_num_users: 1
test_num_users: 1

coverage_area: 0.6
T_min: 8e3
T_max: 9e3
in_window: 10
out_window: 100
n_pos: 10
n_neg: 10

edge_set:
  - [1, 2]
  - [0, 2]
  - [0, 1]
  
compute_channels:
  max_subcarriers: 288
  ue_antenna:
    shape: [1, 1]
  bs_antenna:
    shape: [8, 4]
  # noise_power: -104.0
