scenario: city_14_charlotte_3p5
download: true

batch_size: 16
num_workers: 0
pin_memory: true

exclude_buildings: true
trajectory_kind: neighbor_linear
train_num_users: 1
val_num_users: 1
coverage_area: 0.6
T_min: 1e4
T_max: 10001
in_window: 5
out_window: 20
n_pos: 1
n_neg: 1

edge_set:
  - [1, 2]
  - [0, 2]
  - [0, 1]
  
compute_channels:
  max_subcarriers: 288
  ue_antenna:
    shape: [4, 1]
