_target_: src.DICHASUSDataModule

data_dir: dichasus
files:
  - dichasus-cf02
  - dichasus-cf03
  - dichasus-cf04

train_split: 1.
val_split: 0.0
test_split: 0.0
bs_aggregation:
  # - [0, 2]
  # - [1, 3]
  - [0]
  - [1]
  - [2]
  - [3]

full_cover: False
antennas_per_bs: 8
pin_memory: true
preprocess: dichasus
Tc_pos: 1.5
pair_mode: triplet
n_pos: 2
n_neg: 2
edge_set:
  - [0, 1]
  - [0, 2]
  - [0, 3]
  - [1, 2]
  - [1, 3]
  - [2, 3]

train_seed: 27
val_seed: 123
test_seed: 42

viz_split: test
viz_enabled: false
