defaults:
  - _self_
  - dataset: city_3_houston_3p5
  - model: siameseNN

seed: 42

trainer:
  epochs: 50
  deterministic: true
  num_sanity_val_steps: 2
  log_every_n_steps: 10

wandb:
  project: sheaf-channel-charting
  log_model: false
