defaults:
  - _self_
  - dataset: dichasus_cf0x
  - model: siameseNN
  - orchestrator: cover_sheaf

dataset:
  batch_size: 8192
  num_workers: 0

orchestrator:
  lmb_min: 0
  lmb_max: 1e-1
  lmb_schedule: cosine

logger:
  _target_: lightning.pytorch.loggers.WandbLogger
  project: sheaf_cc_daylight
  name: ${hydra:runtime.choices.orchestrator}_${now:%Y-%m-%d}_${now:%H-%M-%S}
  log_model: false

save_model: true

seed: 80

num_folds: 4
anchor_seed: 80
triplet_seeds: [1,2,3,4]
learning_rates: [1e-3, 1e-3, 1e-4, 1e-4]
separate_fold_runs: false

trainer:
  max_epochs: 5
  accelerator: auto
  devices: 1
  deterministic: false      
  num_sanity_val_steps: 0
  log_every_n_steps: 5

callbacks:

hydra:
  mode: MULTIRUN
  sweeper:
    params:
      model.use_decoder: false
